// Class automatically generated by Dev-C++ New Class wizard

#ifndef AVL_H
#define AVL_H
#include "BinNode.h"

/*
 * No description
 */
class Avl
{
	public:
		// class constructor
		Avl();
		// class destructor
		~Avl();
		
		
		bool buscar( string llave );
		
		void insertar( string key, int element );
		void eliminar( string key );
		
		void sortedDump();
		void prettyPrint();
		
		
		BinNode* getRoot();
		
	private:
        void imprimir( BinNode* raiz );
        void imprimirBonito( BinNode* raiz);
        
        void balancear( BinNode* nodo );
        
        BinNode* buscarEn( BinNode* n, string llave);
        BinNode* _root;
        int _nodesCount;    
};

#endif // AVL_H
