// Class automatically generated by Dev-C++ New Class wizard

#ifndef AVL_H
#define AVL_H
#include "BinNode.h"

/*
 * No description
 */
class Avl
{
	public:
		// class constructor
		Avl();
		// class destructor
		~Avl();
		
		bool buscar( string llave );
		bool buscarEn( BinNode* n, string llave);
		void insertar( string key, int element );
		void eliminar( string key );
		
		
	private:
        BinNode* _root;
        int _nodesCount;
            
            
};

#endif // AVL_H
